### ISSUE TITLE
Error when running npm run start

### ISSUE THREAD

**Issue by rgknp** [ilfrich/couchdb-to-mongodb#7]
Getting below error when running the code:

C:\git\couchdb-to-mongodb>npm run start 
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> couchdb-to-mongodb@1.0.0 start
> babel-node couch-to-mongo.js

(node:25172) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25172) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:25172) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:25172) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
(node:25172) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
**Error Error: Password contains an illegal unescaped character**
    at parseConnectionString (C:\git\couchdb-to-mongodb\node_modules\mongodb\lib\url_parser.js:298:13)
    at parseHandler (C:\git\couchdb-to-mongodb\node_modules\mongodb\lib\url_parser.js:129:14)
    at module.exports (C:\git\couchdb-to-mongodb\node_modules\mongodb\lib\url_parser.js:25:12)
    at deprecated (node:internal/util:124:12)
    at connect (C:\git\couchdb-to-mongodb\node_modules\mongodb\lib\operations\mongo_client_ops.js:195:3)
    at connectOp (C:\git\couchdb-to-mongodb\node_modules\mongodb\lib\operations\mongo_client_ops.js:284:3)
    at C:\git\couchdb-to-mongodb\node_modules\mongodb\lib\utils.js:433:24
    at new Promise (<anonymous>)
    at executeOperation (C:\git\couchdb-to-mongodb\node_modules\mongodb\lib\utils.js:428:10)
    at MongoClient.connect (C:\git\couchdb-to-mongodb\node_modules\mongodb\lib\mongo_client.js:175:10)

C:\git\couchdb-to-mongodb>

**Comment by rgknp** [comment]
For context, I am trying to migrate a IBM Cloudant Database (Couch DB based) to Azure Cosmos DB (Mongo API). 

Thanks

**Comment by ilfrich** [comment]
Looks like your `MONGO` environment variable contains some invalid character. If there are special characters or spaces in the username or password (as part of the mongo connection url), you might have to URL encode them. So, if your username/password contains anything like `$`, `#`, `%`, `(`, `)`, `[`, `]`, ... etc, please replace them in the `MONGO` environment variable with the corresponding code: https://www.tutorialspoint.com/html/html_url_encoding.htm (like `%7d` for `}`) - this does not apply to the `:` and `/` in the base URL's http://, but only to the username/password
